# Generated by Django 4.1 on 2023-04-11 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employeeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('salary', models.ImageField(upload_to='')),
                ('company', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('mobile', models.BigIntegerField()),
                ('emailid', models.EmailField(max_length=100)),
                ('address', models.CharField(max_length=100)),
            ],
        ),
    ]
